//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 08:06:01 PM COT 
//


package co.com.canonical.bpel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.canonical.bpel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.canonical.bpel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo }
     * 
     */
    public Process.DomainEventsInfo createProcessDomainEventsInfo() {
        return new Process.DomainEventsInfo();
    }

    /**
     * Create an instance of {@link Process.OperationalInfo }
     * 
     */
    public Process.OperationalInfo createProcessOperationalInfo() {
        return new Process.OperationalInfo();
    }

    /**
     * Create an instance of {@link Process.ScheduledInfo }
     * 
     */
    public Process.ScheduledInfo createProcessScheduledInfo() {
        return new Process.ScheduledInfo();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.AlertOnAir }
     * 
     */
    public Process.DomainEventsInfo.AlertOnAir createProcessDomainEventsInfoAlertOnAir() {
        return new Process.DomainEventsInfo.AlertOnAir();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.OnAirShopping }
     * 
     */
    public Process.DomainEventsInfo.OnAirShopping createProcessDomainEventsInfoOnAirShopping() {
        return new Process.DomainEventsInfo.OnAirShopping();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.ActualOutgate }
     * 
     */
    public Process.DomainEventsInfo.ActualOutgate createProcessDomainEventsInfoActualOutgate() {
        return new Process.DomainEventsInfo.ActualOutgate();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.ActualIngate }
     * 
     */
    public Process.DomainEventsInfo.ActualIngate createProcessDomainEventsInfoActualIngate() {
        return new Process.DomainEventsInfo.ActualIngate();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.EstimatedOutgate }
     * 
     */
    public Process.DomainEventsInfo.EstimatedOutgate createProcessDomainEventsInfoEstimatedOutgate() {
        return new Process.DomainEventsInfo.EstimatedOutgate();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.EstimatedIngate }
     * 
     */
    public Process.DomainEventsInfo.EstimatedIngate createProcessDomainEventsInfoEstimatedIngate() {
        return new Process.DomainEventsInfo.EstimatedIngate();
    }

    /**
     * Create an instance of {@link Process.DomainEventsInfo.CancelFlight }
     * 
     */
    public Process.DomainEventsInfo.CancelFlight createProcessDomainEventsInfoCancelFlight() {
        return new Process.DomainEventsInfo.CancelFlight();
    }

}
