//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 08:06:01 PM COT 
//


package co.com.canonical.bpel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operational-info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="departure-airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="arrival-airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="scheduled-info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="estimated-outgate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="estimated-ingate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="estimated-outgate-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="estimated-ingate-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="domain-events-info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="alert-on-air">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="alert-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="on-air-shopping">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="credit-card-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="transaction-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="actual-outgate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="actual-ingate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="estimated-outgate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="estimated-ingate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cancel-flight">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="external-key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operationalInfo",
    "scheduledInfo",
    "domainEventsInfo"
})
@XmlRootElement(name = "process")
public class Process {

    @XmlElement(name = "operational-info", required = true)
    protected Process.OperationalInfo operationalInfo;
    @XmlElement(name = "scheduled-info", required = true)
    protected Process.ScheduledInfo scheduledInfo;
    @XmlElement(name = "domain-events-info", required = true)
    protected Process.DomainEventsInfo domainEventsInfo;
    @XmlAttribute(name = "external-key")
    protected String externalKey;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the operationalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Process.OperationalInfo }
     *     
     */
    public Process.OperationalInfo getOperationalInfo() {
        return operationalInfo;
    }

    /**
     * Sets the value of the operationalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process.OperationalInfo }
     *     
     */
    public void setOperationalInfo(Process.OperationalInfo value) {
        this.operationalInfo = value;
    }

    /**
     * Gets the value of the scheduledInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Process.ScheduledInfo }
     *     
     */
    public Process.ScheduledInfo getScheduledInfo() {
        return scheduledInfo;
    }

    /**
     * Sets the value of the scheduledInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process.ScheduledInfo }
     *     
     */
    public void setScheduledInfo(Process.ScheduledInfo value) {
        this.scheduledInfo = value;
    }

    /**
     * Gets the value of the domainEventsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Process.DomainEventsInfo }
     *     
     */
    public Process.DomainEventsInfo getDomainEventsInfo() {
        return domainEventsInfo;
    }

    /**
     * Sets the value of the domainEventsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process.DomainEventsInfo }
     *     
     */
    public void setDomainEventsInfo(Process.DomainEventsInfo value) {
        this.domainEventsInfo = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="alert-on-air">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="alert-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="on-air-shopping">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="credit-card-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="transaction-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="actual-outgate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="actual-ingate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="estimated-outgate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="estimated-ingate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cancel-flight">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alertOnAir",
        "onAirShopping",
        "actualOutgate",
        "actualIngate",
        "estimatedOutgate",
        "estimatedIngate",
        "cancelFlight"
    })
    public static class DomainEventsInfo {

        @XmlElement(name = "alert-on-air", required = true)
        protected Process.DomainEventsInfo.AlertOnAir alertOnAir;
        @XmlElement(name = "on-air-shopping", required = true)
        protected Process.DomainEventsInfo.OnAirShopping onAirShopping;
        @XmlElement(name = "actual-outgate", required = true)
        protected Process.DomainEventsInfo.ActualOutgate actualOutgate;
        @XmlElement(name = "actual-ingate", required = true)
        protected Process.DomainEventsInfo.ActualIngate actualIngate;
        @XmlElement(name = "estimated-outgate", required = true)
        protected Process.DomainEventsInfo.EstimatedOutgate estimatedOutgate;
        @XmlElement(name = "estimated-ingate", required = true)
        protected Process.DomainEventsInfo.EstimatedIngate estimatedIngate;
        @XmlElement(name = "cancel-flight", required = true)
        protected Process.DomainEventsInfo.CancelFlight cancelFlight;

        /**
         * Gets the value of the alertOnAir property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.AlertOnAir }
         *     
         */
        public Process.DomainEventsInfo.AlertOnAir getAlertOnAir() {
            return alertOnAir;
        }

        /**
         * Sets the value of the alertOnAir property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.AlertOnAir }
         *     
         */
        public void setAlertOnAir(Process.DomainEventsInfo.AlertOnAir value) {
            this.alertOnAir = value;
        }

        /**
         * Gets the value of the onAirShopping property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.OnAirShopping }
         *     
         */
        public Process.DomainEventsInfo.OnAirShopping getOnAirShopping() {
            return onAirShopping;
        }

        /**
         * Sets the value of the onAirShopping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.OnAirShopping }
         *     
         */
        public void setOnAirShopping(Process.DomainEventsInfo.OnAirShopping value) {
            this.onAirShopping = value;
        }

        /**
         * Gets the value of the actualOutgate property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.ActualOutgate }
         *     
         */
        public Process.DomainEventsInfo.ActualOutgate getActualOutgate() {
            return actualOutgate;
        }

        /**
         * Sets the value of the actualOutgate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.ActualOutgate }
         *     
         */
        public void setActualOutgate(Process.DomainEventsInfo.ActualOutgate value) {
            this.actualOutgate = value;
        }

        /**
         * Gets the value of the actualIngate property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.ActualIngate }
         *     
         */
        public Process.DomainEventsInfo.ActualIngate getActualIngate() {
            return actualIngate;
        }

        /**
         * Sets the value of the actualIngate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.ActualIngate }
         *     
         */
        public void setActualIngate(Process.DomainEventsInfo.ActualIngate value) {
            this.actualIngate = value;
        }

        /**
         * Gets the value of the estimatedOutgate property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.EstimatedOutgate }
         *     
         */
        public Process.DomainEventsInfo.EstimatedOutgate getEstimatedOutgate() {
            return estimatedOutgate;
        }

        /**
         * Sets the value of the estimatedOutgate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.EstimatedOutgate }
         *     
         */
        public void setEstimatedOutgate(Process.DomainEventsInfo.EstimatedOutgate value) {
            this.estimatedOutgate = value;
        }

        /**
         * Gets the value of the estimatedIngate property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.EstimatedIngate }
         *     
         */
        public Process.DomainEventsInfo.EstimatedIngate getEstimatedIngate() {
            return estimatedIngate;
        }

        /**
         * Sets the value of the estimatedIngate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.EstimatedIngate }
         *     
         */
        public void setEstimatedIngate(Process.DomainEventsInfo.EstimatedIngate value) {
            this.estimatedIngate = value;
        }

        /**
         * Gets the value of the cancelFlight property.
         * 
         * @return
         *     possible object is
         *     {@link Process.DomainEventsInfo.CancelFlight }
         *     
         */
        public Process.DomainEventsInfo.CancelFlight getCancelFlight() {
            return cancelFlight;
        }

        /**
         * Sets the value of the cancelFlight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.DomainEventsInfo.CancelFlight }
         *     
         */
        public void setCancelFlight(Process.DomainEventsInfo.CancelFlight value) {
            this.cancelFlight = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "gateCode",
            "fuelPercentage"
        })
        public static class ActualIngate {

            @XmlElement(required = true)
            protected String date;
            @XmlElement(name = "gate-code", required = true)
            protected String gateCode;
            @XmlElement(name = "fuel-percentage", required = true)
            protected String fuelPercentage;

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the gateCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGateCode() {
                return gateCode;
            }

            /**
             * Sets the value of the gateCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGateCode(String value) {
                this.gateCode = value;
            }

            /**
             * Gets the value of the fuelPercentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFuelPercentage() {
                return fuelPercentage;
            }

            /**
             * Sets the value of the fuelPercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFuelPercentage(String value) {
                this.fuelPercentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "gateCode",
            "fuelPercentage"
        })
        public static class ActualOutgate {

            @XmlElement(required = true)
            protected String date;
            @XmlElement(name = "gate-code", required = true)
            protected String gateCode;
            @XmlElement(name = "fuel-percentage", required = true)
            protected String fuelPercentage;

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the gateCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGateCode() {
                return gateCode;
            }

            /**
             * Sets the value of the gateCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGateCode(String value) {
                this.gateCode = value;
            }

            /**
             * Gets the value of the fuelPercentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFuelPercentage() {
                return fuelPercentage;
            }

            /**
             * Sets the value of the fuelPercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFuelPercentage(String value) {
                this.fuelPercentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="alert-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "alertType"
        })
        public static class AlertOnAir {

            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "alert-type", required = true)
            protected String alertType;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the alertType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlertType() {
                return alertType;
            }

            /**
             * Sets the value of the alertType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlertType(String value) {
                this.alertType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description"
        })
        public static class CancelFlight {

            @XmlElement(required = true)
            protected String description;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "gateCode",
            "fuelPercentage"
        })
        public static class EstimatedIngate {

            @XmlElement(required = true)
            protected String date;
            @XmlElement(name = "gate-code", required = true)
            protected String gateCode;
            @XmlElement(name = "fuel-percentage", required = true)
            protected String fuelPercentage;

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the gateCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGateCode() {
                return gateCode;
            }

            /**
             * Sets the value of the gateCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGateCode(String value) {
                this.gateCode = value;
            }

            /**
             * Gets the value of the fuelPercentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFuelPercentage() {
                return fuelPercentage;
            }

            /**
             * Sets the value of the fuelPercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFuelPercentage(String value) {
                this.fuelPercentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "gateCode",
            "fuelPercentage"
        })
        public static class EstimatedOutgate {

            @XmlElement(required = true)
            protected String date;
            @XmlElement(name = "gate-code", required = true)
            protected String gateCode;
            @XmlElement(name = "fuel-percentage", required = true)
            protected String fuelPercentage;

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the gateCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGateCode() {
                return gateCode;
            }

            /**
             * Sets the value of the gateCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGateCode(String value) {
                this.gateCode = value;
            }

            /**
             * Gets the value of the fuelPercentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFuelPercentage() {
                return fuelPercentage;
            }

            /**
             * Sets the value of the fuelPercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFuelPercentage(String value) {
                this.fuelPercentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="credit-card-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="transaction-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "creditCardNumber",
            "value",
            "transactionDate"
        })
        public static class OnAirShopping {

            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "credit-card-number", required = true)
            protected String creditCardNumber;
            @XmlElement(required = true)
            protected String value;
            @XmlElement(name = "transaction-date", required = true)
            protected String transactionDate;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the creditCardNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreditCardNumber() {
                return creditCardNumber;
            }

            /**
             * Sets the value of the creditCardNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreditCardNumber(String value) {
                this.creditCardNumber = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the transactionDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionDate() {
                return transactionDate;
            }

            /**
             * Sets the value of the transactionDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionDate(String value) {
                this.transactionDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="departure-airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="arrival-airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "departureAirport",
        "arrivalAirport"
    })
    public static class OperationalInfo {

        @XmlElement(name = "departure-airport", required = true)
        protected String departureAirport;
        @XmlElement(name = "arrival-airport", required = true)
        protected String arrivalAirport;

        /**
         * Gets the value of the departureAirport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartureAirport() {
            return departureAirport;
        }

        /**
         * Sets the value of the departureAirport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartureAirport(String value) {
            this.departureAirport = value;
        }

        /**
         * Gets the value of the arrivalAirport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrivalAirport() {
            return arrivalAirport;
        }

        /**
         * Sets the value of the arrivalAirport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrivalAirport(String value) {
            this.arrivalAirport = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="estimated-outgate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="estimated-ingate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="estimated-outgate-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="estimated-ingate-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estimatedOutgate",
        "estimatedIngate",
        "estimatedOutgateTime",
        "estimatedIngateTime"
    })
    public static class ScheduledInfo {

        @XmlElement(name = "estimated-outgate", required = true)
        protected String estimatedOutgate;
        @XmlElement(name = "estimated-ingate", required = true)
        protected String estimatedIngate;
        @XmlElement(name = "estimated-outgate-time", required = true)
        protected String estimatedOutgateTime;
        @XmlElement(name = "estimated-ingate-time", required = true)
        protected String estimatedIngateTime;

        /**
         * Gets the value of the estimatedOutgate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedOutgate() {
            return estimatedOutgate;
        }

        /**
         * Sets the value of the estimatedOutgate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedOutgate(String value) {
            this.estimatedOutgate = value;
        }

        /**
         * Gets the value of the estimatedIngate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedIngate() {
            return estimatedIngate;
        }

        /**
         * Sets the value of the estimatedIngate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedIngate(String value) {
            this.estimatedIngate = value;
        }

        /**
         * Gets the value of the estimatedOutgateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedOutgateTime() {
            return estimatedOutgateTime;
        }

        /**
         * Sets the value of the estimatedOutgateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedOutgateTime(String value) {
            this.estimatedOutgateTime = value;
        }

        /**
         * Gets the value of the estimatedIngateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedIngateTime() {
            return estimatedIngateTime;
        }

        /**
         * Sets the value of the estimatedIngateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedIngateTime(String value) {
            this.estimatedIngateTime = value;
        }

    }

}
