//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.12 at 10:30:38 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/pica_aes_fuse/pica_aes/bpelprocess", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.canonical.responseFuse;
