//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 07:12:09 PM COT 
//


package co.com.canonical.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usage-parm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tsn" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tso" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="tsi" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "alertType"
})
public class AlertOnAir {

    @XmlElement(name = "description", required = true)
    protected String description;
    @XmlElement(name = "alert-type", required = true)
    protected String alertType;
    
    /** Getter.
     * @return the status
     */
    public String getDescription() {
        return description;
    }

    /** Setter.
     * @param status the status to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** Getter.
     * @return the status
     */
    public String getAlertType() {
        return alertType;
    }

    /** Setter.
     * @param status the status to set
     */
    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

}
